describe('Login Test', () => {
  it('Login 5 Times', () => {
    cy.visit('/account/login', { failOnStatusCode: false })
    const login = () => {
      cy.get("input[name='Email']")
        .focus()
        .type('test@o-k.tech')
      cy.get("input[name='Pass']")
        .focus()
        .type('1')
      cy.get("button.success[type='submit']").click()
      cy.get("[href='/account/logout']").click()
      cy.get("[href='/account/login']").click()
    }
    login()
    login()
    login()
    login()
    login()
    login()
    login()
    login()
    login()
    login()
    login()
    login()
    login()
    login()
    login()
    login()
    login()
    login()
    login()
    login()
    login()
    login()
    login()
    login()
    login()
  })
})
