describe('Login Test', () => {
  it('Login 5 Times', () => {
    cy.visit('/login', { failOnStatusCode: false })
    const login = () => {
      cy.get("input[name='Email']")
        .focus()
        .type('reg137@o-k.tech')
      cy.get("input[name='Pass']")
        .focus()
        .type('a123456')
      cy.get("button.success[type='submit']").click()
      cy.get("[href='/logout']").click()
      cy.get("[href='/super_login']").click()
    }
    login()
    login()
    login()
    login()
    login()
    login()
    login()
    login()
    login()
    login()
    login()
    login()
    login()
    login()
    login()
    login()
    login()
    login()
    login()
    login()
    login()
    login()
    login()
    login()
    login()
  })
})
